const PLANT_DEFS = {
  sunflower:    { name: 'Sunflower',    cost: 50,  cd: 7.5,  hp: 100, desc: 'Produces extra sun. Plant lots of these!' },
  peashooter:   { name: 'Peashooter',   cost: 100, cd: 7.5,  hp: 100, desc: 'Shoots peas at zombies in its row.' },
  cherrybomb:   { name: 'Cherry Bomb',   cost: 150, cd: 50,   hp: 100, desc: 'Blows up all zombies in a 3x3 area.' },
  wallnut:      { name: 'Wall-nut',      cost: 50,  cd: 30,   hp: 4000, desc: 'Tough shell that blocks zombies.' },
  potatomine:   { name: 'Potato Mine',   cost: 25,  cd: 30,   hp: 100, desc: 'Arms after 14s, then explodes on contact.' },
  snowpea:      { name: 'Snow Pea',      cost: 175, cd: 7.5,  hp: 100, desc: 'Frozen peas damage and slow zombies.' },
  chomper:      { name: 'Chomper',      cost: 150, cd: 7.5,  hp: 100, desc: 'Eats a whole zombie, then chews for a while.' },
  repeater:     { name: 'Repeater',     cost: 200, cd: 7.5,  hp: 100, desc: 'Shoots two peas at a time.' },
  puffshroom:   { name: 'Puff-shroom',   cost: 0,   cd: 7.5,  hp: 100, desc: 'Free, short-range. Only lives 20 seconds.' },
  sunshroom:    { name: 'Sun-shroom',    cost: 25,  cd: 7.5,  hp: 100, desc: 'Makes small sun, grows to make normal sun.' },
  fumeshroom:   { name: 'Fume-shroom',   cost: 75,  cd: 7.5,  hp: 100, desc: 'Fumes pass through screen doors.' },
  gravebuster:  { name: 'Grave Buster',  cost: 75,  cd: 7.5,  hp: 100, desc: 'Planted on graves to consume them.' },
  hypnoshroom:  { name: 'Hypno-shroom',  cost: 75,  cd: 7.5,  hp: 100, desc: 'Zombies that eat it fight for you!' },
  scaredyshroom:{ name: 'Scaredy-shroom',cost: 25,  cd: 7.5,  hp: 100, desc: 'Shoots until zombies get close, then hides.' },
  iceshroom:    { name: 'Ice-shroom',    cost: 75,  cd: 50,   hp: 100, desc: 'Freezes ALL zombies on screen briefly.' },
  doomshroom:   { name: 'Doom-shroom',   cost: 125, cd: 50,   hp: 100, desc: 'Huge explosion, leaves a crater.' },
  lilypad:      { name: 'Lily Pad',      cost: 25,  cd: 7.5,  hp: 100, desc: 'Lets plants sit on water.' },
  squash:       { name: 'Squash',       cost: 50,  cd: 30,   hp: 100, desc: 'Jumps on and crushes a nearby zombie.' },
  threepeater:  { name: 'Threepeater',  cost: 325, cd: 7.5,  hp: 100, desc: 'Shoots peas in three rows.' },
  tanglekelp:   { name: 'Tangle Kelp',   cost: 25,  cd: 30,   hp: 100, desc: 'Aquatic. Drags the first zombie underwater.' },
  jalapeno:     { name: 'Jalapeno',     cost: 125, cd: 50,   hp: 100, desc: 'Incinerates an entire row of zombies.' },
  spikewalk:    { name: 'Spikewalk',    cost: 100, cd: 7.5,  hp: 100, desc: 'Damages zombies that walk over it.' },
  torchwood:    { name: 'Torchwood',    cost: 175, cd: 7.5,  hp: 100, desc: 'Peas passing through become fire peas.' },
  tallnut:      { name: 'Tall-nut',      cost: 125, cd: 30,   hp: 8000, desc: 'Extra tough. Blocks high throws and vaults.' },
  seashroom:    { name: 'Sea-shroom',    cost: 0,   cd: 7.5,  hp: 100, desc: 'Free aquatic puff-shroom. Lives 20 seconds.' },
  plantern:     { name: 'Plantern',     cost: 25,  cd: 30,   hp: 100, desc: 'Reveals fog in a 3x3 area.' },
  cactus:       { name: 'Cactus',       cost: 125, cd: 7.5,  hp: 100, desc: 'Shoots spikes that pop balloons.' },
  blover:       { name: 'Blover',       cost: 100, cd: 7.5,  hp: 100, desc: 'Blows away balloon zombies and fog.' },
  splitpea:     { name: 'Split Pea',     cost: 125, cd: 7.5,  hp: 100, desc: 'Shoots peas forward AND backward.' },
  starfruit:    { name: 'Starfruit',    cost: 125, cd: 7.5,  hp: 100, desc: 'Shoots stars in 5 directions.' },
  pumpkin:      { name: 'Pumpkin',      cost: 100, cd: 30,   hp: 4000, desc: 'Protective shell for another plant.' },
  magnetshroom: { name: 'Magnet-shroom', cost: 100, cd: 7.5,  hp: 100, desc: 'Steals metal objects from zombies.' },
  cabbagepult:  { name: 'Cabbage-pult',  cost: 100, cd: 7.5,  hp: 100, desc: 'Lobs cabbages that deal splash damage.' },
  kernelpult:   { name: 'Kernel-pult',   cost: 100, cd: 7.5,  hp: 100, desc: 'Kernels plus butter that stuns.' },
  coffeebean:   { name: 'Coffee Bean',   cost: 75,  cd: 7.5,  hp: 100, desc: 'Wakes up a sleeping mushroom.' },
  umbrellaleaf: { name: 'Umbrella Leaf', cost: 100, cd: 7.5,  hp: 100, desc: 'Protects nearby plants from the sky.' },
  marigold:     { name: 'Marigold',     cost: 50,  cd: 30,   hp: 100, desc: 'Produces silver and gold coins.' },
  melonpult:    { name: 'Melon-pult',    cost: 300, cd: 30,   hp: 100, desc: 'Melons deal heavy splash damage.' },
  gatlingpea:   { name: 'Gatling Pea',   cost: 250, cd: 50,   hp: 100, desc: 'Plant on a Repeater. Shoots 4 peas fast.' },
  twinsunflower:{ name: 'Twin Sunflower',cost: 150, cd: 50,   hp: 100, desc: 'Plant on a Sunflower. Makes double sun.' },
  wintermelon:  { name: 'Winter Melon',  cost: 200, cd: 50,   hp: 100, desc: 'Plant on a Melon-pult. Splash + slow.' },
  goldmagnet:   { name: 'Gold Magnet',   cost: 50,  cd: 50,   hp: 100, desc: 'Plant on a Magnet-shroom. Makes coins.' },
  imitater:     { name: 'Imitater',     cost: 0,   cd: 7.5,  hp: 100, desc: 'Becomes a copy of any other plant.' },
};

const ZOMBIE_DEFS = {
  basic:        { name: 'Basic Zombie',       hp: 200,  speed: 22, brain: 25,  desc: 'Your average zombie. Shuffles, eats brains.' },
  conehead:     { name: 'Conehead Zombie',    hp: 560,  speed: 22, brain: 50,  desc: 'Traffic cone gives extra protection.' },
  buckethead:   { name: 'Buckethead Zombie',  hp: 1300, speed: 22, brain: 100, desc: 'Metal bucket is very tough.' },
  flag:         { name: 'Flag Zombie',        hp: 200,  speed: 24, brain: 0,   desc: 'Signals a huge wave of zombies.' },
  polevault:    { name: 'Pole Vaulting Zombie', hp: 500, speed: 30, brain: 75, desc: 'Vaults over the first plant it meets.' },
  football:     { name: 'Football Zombie',    hp: 1600, speed: 45, brain: 150, desc: 'Fast and tough. A real touchdown.' },
  dancing:      { name: 'Dancing Zombie',     hp: 500,  speed: 20, brain: 150, desc: 'Summons backup dancers.' },
  backupdancer: { name: 'Backup Dancer',     hp: 200,  speed: 24, brain: 25,  desc: 'Dances in from behind.' },
  balloon:      { name: 'Balloon Zombie',     hp: 200,  speed: 26, brain: 75,  desc: 'Floats above ground attacks. Pops and drops.' },
  screendoor:   { name: 'Screen Door Zombie', hp: 1100, speed: 22, brain: 100, desc: 'Door blocks most projectiles.' },
  gargantuar:   { name: 'Gargantuar',        hp: 3000, speed: 15, brain: 300, desc: 'Massive. Throws an Imp at half health.' },
  imp:          { name: 'Imp',               hp: 200,  speed: 32, brain: 25,  desc: 'Small and quick.' },
  bungee:       { name: 'Bungee Zombie',      hp: 200,  speed: 0,  brain: 100, desc: 'Drops from the sky to steal a plant.' },
  catapult:     { name: 'Catapult Zombie',    hp: 500,  speed: 15, brain: 150, desc: 'Lobs basketballs at your plants.' },
  yeti:         { name: 'Zombie Yeti',        hp: 200,  speed: 60, brain: 0,   desc: 'Rare! Runs away when hurt. Drops a diamond.' },
  snorkel:      { name: 'Snorkel Zombie',     hp: 200,  speed: 20, brain: 75,  desc: 'Swims underwater, surfaces to eat.' },
  zomboni:      { name: 'Zomboni',           hp: 1300, speed: 20, brain: 150, desc: 'Leaves an ice trail plants cannot use.' },
  dolphinrider: { name: 'Dolphin Rider Zombie', hp: 500, speed: 35, brain: 100, desc: 'Dolphin jumps over the first plant.' },
  jackinthebox: { name: 'Jack-in-the-Box Zombie', hp: 500, speed: 26, brain: 100, desc: 'Explodes after a short timer.' },
  pogo:         { name: 'Pogo Zombie',        hp: 500,  speed: 40, brain: 100, desc: 'Bounces over the first plant.' },
  digger:       { name: 'Digger Zombie',      hp: 500,  speed: 25, brain: 100, desc: 'Digs behind your plants, then walks backward.' },
  bobsled:      { name: 'Zombie Bobsled Team', hp: 200, speed: 50, brain: 150, desc: 'Four zombies on a bobsled. Needs ice.' },
};

const A1_UNLOCKS = ['peashooter', 'sunflower', 'cherrybomb', 'wallnut', 'potatomine', 'snowpea', 'chomper', 'repeater', 'puffshroom', 'sunshroom'];
const A2_UNLOCKS = ['fumeshroom', 'gravebuster', 'hypnoshroom', 'scaredyshroom', 'iceshroom', 'doomshroom', 'lilypad', 'squash', 'threepeater', 'tanglekelp',
  'jalapeno', 'spikewalk', 'torchwood', 'tallnut', 'seashroom', 'plantern', 'cactus', 'blover', 'splitpea', 'starfruit',
  'pumpkin', 'magnetshroom', 'cabbagepult', 'kernelpult', 'coffeebean', 'umbrellaleaf', 'marigold', 'melonpult', 'gatlingpea', 'twinsunflower',
  'wintermelon', 'goldmagnet', 'imitater'];

function packetsForLevel(levelId) {
  const adv = levelId[0] === '1' ? 1 : 2;
  const n = parseInt(levelId.split('-')[1]);
  const unlocks = adv === 1 ? A1_UNLOCKS : A2_UNLOCKS;
  const out = [];
  for (let i = 0; i < n; i++) {
    const p = unlocks[i];
    if (p && !out.includes(p)) out.push(p);
  }
  return out;
}

const LEVELS = {
  '1-1': { theme: 'day', startSun: 50, packets: ['peashooter'], reward: 'sunflower',
    waves: [
      { t: 25, spawns: [['basic', 1]] },
      { t: 55, spawns: [['basic', 1]] },
      { t: 85, spawns: [['basic', 2, 8]] },
      { t: 120, spawns: [['basic', 3, 10]], huge: true },
    ]},
  '1-2': { theme: 'day', startSun: 50, packets: ['peashooter', 'sunflower'], reward: 'cherrybomb',
    waves: [
      { t: 20, spawns: [['basic', 1]] },
      { t: 50, spawns: [['basic', 2, 8]] },
      { t: 80, spawns: [['basic', 1], ['conehead', 1]] },
      { t: 115, spawns: [['basic', 2, 8], ['conehead', 1]] },
      { t: 150, spawns: [['basic', 3, 9], ['conehead', 2, 12]], huge: true },
    ]},
  '1-3': { theme: 'day', startSun: 50, packets: ['peashooter', 'sunflower', 'cherrybomb'], reward: 'wallnut',
    waves: [
      { t: 20, spawns: [['basic', 2, 8]] },
      { t: 55, spawns: [['conehead', 1], ['basic', 2, 8]] },
      { t: 90, spawns: [['basic', 2, 8], ['conehead', 2, 10]] },
      { t: 125, spawns: [['buckethead', 1], ['basic', 2, 8]] },
      { t: 160, spawns: [['basic', 3, 8], ['conehead', 2, 10], ['buckethead', 1]], huge: true },
    ]},
  '1-4': { theme: 'day', startSun: 50, packets: ['peashooter', 'sunflower', 'cherrybomb', 'wallnut'], reward: 'potatomine',
    waves: [
      { t: 18, spawns: [['basic', 2, 8]] },
      { t: 50, spawns: [['conehead', 2, 9]] },
      { t: 85, spawns: [['basic', 2, 7], ['buckethead', 1]] },
      { t: 120, spawns: [['conehead', 2, 8], ['basic', 2, 8]] },
      { t: 155, spawns: [['buckethead', 2, 12], ['basic', 3, 8], ['conehead', 1]], huge: true },
    ]},
  '1-5': { theme: 'day', startSun: 50, packets: ['peashooter', 'sunflower', 'cherrybomb', 'wallnut', 'potatomine'], reward: 'snowpea',
    waves: [
      { t: 18, spawns: [['basic', 2, 7]] },
      { t: 48, spawns: [['polevault', 1], ['basic', 2, 8]] },
      { t: 82, spawns: [['conehead', 2, 8], ['buckethead', 1]] },
      { t: 118, spawns: [['basic', 3, 8], ['polevault', 1]] },
      { t: 152, spawns: [['buckethead', 2, 10], ['conehead', 2, 8], ['basic', 2, 8]], huge: true },
    ]},
  '1-6': { theme: 'night', startSun: 50, packets: ['peashooter', 'sunflower', 'cherrybomb', 'wallnut', 'potatomine', 'snowpea'], reward: 'chomper',
    waves: [
      { t: 18, spawns: [['basic', 2, 7]] },
      { t: 50, spawns: [['conehead', 2, 8], ['basic', 1]] },
      { t: 85, spawns: [['buckethead', 1], ['basic', 2, 8]] },
      { t: 120, spawns: [['conehead', 2, 8], ['basic', 2, 7]] },
      { t: 155, spawns: [['buckethead', 2, 10], ['conehead', 2, 8], ['basic', 3, 8]], huge: true },
    ]},
  '1-7': { theme: 'night', startSun: 50, packets: ['peashooter', 'sunflower', 'cherrybomb', 'wallnut', 'potatomine', 'snowpea', 'chomper'], reward: 'repeater',
    waves: [
      { t: 18, spawns: [['basic', 2, 7], ['football', 1]] },
      { t: 52, spawns: [['conehead', 2, 8], ['basic', 2, 7]] },
      { t: 88, spawns: [['football', 1], ['buckethead', 1], ['basic', 2, 8]] },
      { t: 124, spawns: [['conehead', 3, 8], ['basic', 2, 7]] },
      { t: 158, spawns: [['football', 2, 14], ['buckethead', 2, 10], ['basic', 3, 8]], huge: true },
    ]},
  '1-8': { theme: 'night', startSun: 50, packets: ['peashooter', 'sunflower', 'cherrybomb', 'wallnut', 'potatomine', 'snowpea', 'chomper', 'repeater'], reward: 'puffshroom',
    waves: [
      { t: 18, spawns: [['screendoor', 1], ['basic', 2, 7]] },
      { t: 52, spawns: [['conehead', 2, 8], ['football', 1]] },
      { t: 88, spawns: [['screendoor', 1], ['buckethead', 1], ['basic', 2, 8]] },
      { t: 124, spawns: [['football', 1], ['conehead', 2, 8], ['basic', 2, 7]] },
      { t: 158, spawns: [['screendoor', 2, 12], ['buckethead', 2, 10], ['football', 1], ['basic', 3, 8]], huge: true },
    ]},
  '1-9': { theme: 'pool', startSun: 50, packets: ['peashooter', 'sunflower', 'cherrybomb', 'wallnut', 'potatomine', 'snowpea', 'chomper', 'repeater', 'puffshroom'], reward: 'sunshroom',
    waves: [
      { t: 18, spawns: [['basic', 2, 7]] },
      { t: 50, spawns: [['snorkel', 1], ['conehead', 1], ['basic', 2, 7]] },
      { t: 85, spawns: [['dolphinrider', 1], ['basic', 2, 8]] },
      { t: 120, spawns: [['snorkel', 2, 10], ['conehead', 2, 8]] },
      { t: 155, spawns: [['dolphinrider', 2, 12], ['buckethead', 1], ['basic', 3, 8], ['snorkel', 1]], huge: true },
    ]},
  '1-10': { theme: 'roof', startSun: 50, packets: ['peashooter', 'sunflower', 'cherrybomb', 'wallnut', 'potatomine', 'snowpea', 'chomper', 'repeater', 'puffshroom', 'sunshroom'], reward: null,
    waves: [
      { t: 18, spawns: [['basic', 2, 7], ['dancing', 1]] },
      { t: 52, spawns: [['conehead', 2, 8], ['football', 1]] },
      { t: 88, spawns: [['dancing', 1], ['buckethead', 1], ['basic', 2, 8]] },
      { t: 124, spawns: [['gargantuar', 1], ['conehead', 2, 8]] },
      { t: 158, spawns: [['dancing', 2, 14], ['gargantuar', 1], ['buckethead', 2, 10], ['football', 1], ['basic', 3, 8]], huge: true },
    ]},
  '2-1': { theme: 'day', startSun: 50, packets: ['peashooter', 'sunflower', 'cherrybomb', 'wallnut', 'potatomine', 'snowpea', 'chomper', 'repeater', 'puffshroom', 'sunshroom', 'fumeshroom'], reward: 'gravebuster',
    waves: [
      { t: 15, spawns: [['basic', 2, 6]] },
      { t: 45, spawns: [['conehead', 2, 7], ['basic', 2, 6]] },
      { t: 78, spawns: [['buckethead', 1], ['basic', 3, 7]] },
      { t: 112, spawns: [['conehead', 2, 7], ['football', 1]] },
      { t: 145, spawns: [['buckethead', 2, 9], ['conehead', 2, 7], ['basic', 3, 7]], huge: true },
    ]},
  '2-2': { theme: 'day', startSun: 50, packets: ['peashooter', 'sunflower', 'cherrybomb', 'wallnut', 'potatomine', 'snowpea', 'chomper', 'repeater', 'puffshroom', 'sunshroom', 'fumeshroom', 'gravebuster'], reward: 'hypnoshroom',
    waves: [
      { t: 15, spawns: [['basic', 3, 6]] },
      { t: 45, spawns: [['conehead', 2, 7], ['polevault', 1]] },
      { t: 78, spawns: [['buckethead', 2, 9], ['basic', 2, 6]] },
      { t: 112, spawns: [['football', 1], ['conehead', 2, 7]] },
      { t: 145, spawns: [['buckethead', 2, 9], ['polevault', 2, 10], ['basic', 3, 7]], huge: true },
    ]},
  '2-3': { theme: 'day', startSun: 50, packets: ['peashooter', 'sunflower', 'cherrybomb', 'wallnut', 'potatomine', 'snowpea', 'chomper', 'repeater', 'puffshroom', 'sunshroom', 'fumeshroom', 'gravebuster', 'hypnoshroom'], reward: 'scaredyshroom',
    waves: [
      { t: 15, spawns: [['basic', 3, 6], ['conehead', 1]] },
      { t: 45, spawns: [['buckethead', 2, 8], ['basic', 2, 6]] },
      { t: 78, spawns: [['football', 1], ['conehead', 2, 7]] },
      { t: 112, spawns: [['screendoor', 1], ['buckethead', 1], ['basic', 2, 6]] },
      { t: 145, spawns: [['football', 2, 11], ['buckethead', 2, 9], ['conehead', 2, 7]], huge: true },
    ]},
  '2-4': { theme: 'day', startSun: 50, packets: ['peashooter', 'sunflower', 'cherrybomb', 'wallnut', 'potatomine', 'snowpea', 'chomper', 'repeater', 'puffshroom', 'sunshroom', 'fumeshroom', 'gravebuster', 'hypnoshroom', 'scaredyshroom', 'jalapeno', 'spikewalk'], reward: 'iceshroom',
    waves: [
      { t: 15, spawns: [['basic', 3, 6], ['football', 1]] },
      { t: 45, spawns: [['buckethead', 2, 8], ['conehead', 2, 6]] },
      { t: 78, spawns: [['screendoor', 2, 9], ['basic', 2, 6]] },
      { t: 112, spawns: [['football', 1], ['polevault', 2, 8]] },
      { t: 145, spawns: [['buckethead', 3, 9], ['screendoor', 1], ['football', 1], ['basic', 3, 6]], huge: true },
    ]},
  '2-5': { theme: 'day', startSun: 50, packets: ['peashooter', 'sunflower', 'cherrybomb', 'wallnut', 'potatomine', 'snowpea', 'chomper', 'repeater', 'puffshroom', 'sunshroom', 'fumeshroom', 'gravebuster', 'hypnoshroom', 'scaredyshroom', 'jalapeno', 'spikewalk', 'iceshroom', 'torchwood', 'tallnut'], reward: 'doomshroom',
    waves: [
      { t: 15, spawns: [['basic', 3, 6], ['buckethead', 1]] },
      { t: 45, spawns: [['football', 2, 10], ['conehead', 2, 6]] },
      { t: 78, spawns: [['screendoor', 2, 8], ['buckethead', 1]] },
      { t: 112, spawns: [['polevault', 2, 8], ['football', 1], ['basic', 2, 6]] },
      { t: 145, spawns: [['buckethead', 3, 9], ['football', 2, 10], ['screendoor', 1], ['basic', 3, 6]], huge: true },
    ]},
  '2-6': { theme: 'night', startSun: 50, packets: ['peashooter', 'sunflower', 'cherrybomb', 'wallnut', 'potatomine', 'snowpea', 'chomper', 'repeater', 'puffshroom', 'sunshroom', 'fumeshroom', 'gravebuster', 'hypnoshroom', 'scaredyshroom', 'jalapeno', 'spikewalk', 'iceshroom', 'torchwood', 'tallnut', 'doomshroom', 'seashroom', 'plantern'], reward: 'lilypad',
    waves: [
      { t: 15, spawns: [['basic', 3, 6], ['conehead', 2, 6]] },
      { t: 45, spawns: [['buckethead', 2, 8], ['football', 1]] },
      { t: 78, spawns: [['screendoor', 2, 8], ['basic', 3, 6]] },
      { t: 112, spawns: [['football', 2, 10], ['conehead', 2, 6]] },
      { t: 145, spawns: [['buckethead', 3, 9], ['screendoor', 2, 9], ['football', 1], ['basic', 3, 6]], huge: true },
    ]},
  '2-7': { theme: 'night', startSun: 50, packets: ['peashooter', 'sunflower', 'cherrybomb', 'wallnut', 'potatomine', 'snowpea', 'chomper', 'repeater', 'puffshroom', 'sunshroom', 'fumeshroom', 'gravebuster', 'hypnoshroom', 'scaredyshroom', 'jalapeno', 'spikewalk', 'iceshroom', 'torchwood', 'tallnut', 'doomshroom', 'seashroom', 'plantern', 'lilypad', 'cactus', 'blover'], reward: 'squash',
    waves: [
      { t: 15, spawns: [['basic', 3, 6], ['football', 1]] },
      { t: 45, spawns: [['buckethead', 2, 8], ['screendoor', 1]] },
      { t: 78, spawns: [['football', 2, 10], ['conehead', 2, 6]] },
      { t: 112, spawns: [['screendoor', 2, 8], ['buckethead', 2, 8]] },
      { t: 145, spawns: [['football', 2, 10], ['buckethead', 3, 9], ['screendoor', 1], ['basic', 3, 6]], huge: true },
    ]},
  '2-8': { theme: 'night', startSun: 50, packets: ['peashooter', 'sunflower', 'cherrybomb', 'wallnut', 'potatomine', 'snowpea', 'chomper', 'repeater', 'puffshroom', 'sunshroom', 'fumeshroom', 'gravebuster', 'hypnoshroom', 'scaredyshroom', 'jalapeno', 'spikewalk', 'iceshroom', 'torchwood', 'tallnut', 'doomshroom', 'seashroom', 'plantern', 'lilypad', 'cactus', 'blover', 'squash', 'splitpea', 'starfruit'], reward: 'threepeater',
    waves: [
      { t: 15, spawns: [['basic', 4, 6], ['conehead', 2, 6]] },
      { t: 45, spawns: [['buckethead', 2, 8], ['football', 1]] },
      { t: 78, spawns: [['screendoor', 2, 8], ['polevault', 2, 7]] },
      { t: 112, spawns: [['football', 2, 10], ['buckethead', 2, 8]] },
      { t: 145, spawns: [['buckethead', 3, 9], ['football', 2, 10], ['screendoor', 2, 9], ['basic', 4, 6]], huge: true },
    ]},
  '2-9': { theme: 'pool', startSun: 50, packets: ['peashooter', 'sunflower', 'cherrybomb', 'wallnut', 'potatomine', 'snowpea', 'chomper', 'repeater', 'puffshroom', 'sunshroom', 'fumeshroom', 'gravebuster', 'hypnoshroom', 'scaredyshroom', 'jalapeno', 'spikewalk', 'iceshroom', 'torchwood', 'tallnut', 'doomshroom', 'seashroom', 'plantern', 'lilypad', 'cactus', 'blover', 'squash', 'splitpea', 'starfruit', 'threepeater', 'pumpkin', 'magnetshroom'], reward: 'tanglekelp',
    waves: [
      { t: 15, spawns: [['snorkel', 2, 7], ['basic', 2, 6]] },
      { t: 45, spawns: [['dolphinrider', 2, 8], ['conehead', 2, 6]] },
      { t: 78, spawns: [['snorkel', 2, 7], ['buckethead', 1]] },
      { t: 112, spawns: [['dolphinrider', 2, 8], ['football', 1]] },
      { t: 145, spawns: [['snorkel', 3, 8], ['dolphinrider', 2, 9], ['buckethead', 2, 8], ['basic', 3, 6]], huge: true },
    ]},
  '2-10': { theme: 'roof', startSun: 50, packets: ['peashooter', 'sunflower', 'cherrybomb', 'wallnut', 'potatomine', 'snowpea', 'chomper', 'repeater', 'puffshroom', 'sunshroom', 'fumeshroom', 'gravebuster', 'hypnoshroom', 'scaredyshroom', 'jalapeno', 'spikewalk', 'iceshroom', 'torchwood', 'tallnut', 'doomshroom', 'seashroom', 'plantern', 'lilypad', 'cactus', 'blover', 'squash', 'splitpea', 'starfruit', 'threepeater', 'pumpkin', 'magnetshroom', 'tanglekelp', 'cabbagepult', 'kernelpult', 'coffeebean', 'umbrellaleaf', 'marigold', 'melonpult', 'gatlingpea', 'twinsunflower', 'wintermelon', 'goldmagnet', 'imitater'], reward: null,
    waves: [
      { t: 15, spawns: [['dancing', 1], ['basic', 3, 6], ['football', 1]] },
      { t: 45, spawns: [['gargantuar', 1], ['conehead', 2, 6]] },
      { t: 78, spawns: [['dancing', 2, 10], ['buckethead', 2, 8]] },
      { t: 112, spawns: [['gargantuar', 1], ['screendoor', 2, 8], ['football', 1]] },
      { t: 145, spawns: [['gargantuar', 2, 14], ['dancing', 2, 10], ['buckethead', 3, 9], ['football', 2, 10], ['basic', 4, 6]], huge: true },
    ]},
};

const MP_ZOMBIES = ['basic', 'conehead', 'buckethead', 'polevault', 'football', 'dancing', 'balloon', 'screendoor', 'gargantuar', 'snorkel', 'dolphinrider', 'pogo', 'digger', 'jackinthebox', 'zomboni', 'bobsled', 'catapult'];
